### ISSUE TITLE
Any tutorial on how to use it?

### ISSUE THREAD

**Issue by Nisthar** [TheOrchid/Socket#1]
Hi, This is a Nice websocket package.

Btw can you provide any tutorial on how to actually implement it on both sides( server and client)?
Also it would be nice if the tutorial include using the eloquent models with the websocket.

**Comment by tabuna** [comment]
Maybe I'll write a tutorial, in addition to the above items could include work with the session and authorization (id socket To coincide with the id of the database user, it can be used for personal messages), as well as analogue forever in nodejs

Google translate.

**Comment by vesper8** [comment]
Would love to see a more in-depth example of how to use this

**Comment by tabuna** [comment]
I expanded README.md more detailed examples

**Comment by anil1712** [comment]
Getting exception here App::getInstance()
