### ISSUE TITLE
Question: How to send message from server-side?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [TheOrchid/Socket#11]
I have implemented library and both client and server are connected fine. But I am wondering how I can send a message from server side to the client so that client can update HTML view in real time (like notification badge similar to Facebook).

I know we can send message from JS side like:

`socket.send(...)`

But how can I do the same from server-side ? So once server sends message, client reads it, parses it and updates the HTML view in realtime.

Scenario:

- Save a record in database
- Trigger socket event (send message from server-side) for the client side 
- Client side reads message (`onmessage`) and updates html

I have confusion in second point above. 

Maybe Iam not thinking correct in terms of code but hope you get the point of what I am trying to do.

Thanks for the help

**Comment by tabuna** [comment]
I'm not sure that I will have enough knowledge of my English, that would be in an accessible form to describe, but I'll try.

There are several options for behavior:
1) Dependence on the client, for example, the application "Chat", the initiator is the client and transmits data to his interlocutor.

2) (The one you are talking about) Depending on the server, for example, warning about the lack of space on the hard drive, then you must send a message using php to the working socket. I use [**Pawl**](https://github.com/ratchetphp/Pawl) for such purposes.

You need to define a model and add to it an[ **observer**](https://laravel.com/docs/5.4/eloquent#observers) that will send data to the web socket, **listen** to it and update the data on the page.

**Comment by sarfraznawaz2005** [comment]
@tabuna Thanks for the update. I will look into Pawl. Any example of of how observer will integrate with Pawl will be really helpful if you have implemented somewhere. Otherwise you can close this :)

**Comment by tabuna** [comment]
> An example like this is used by me



Socket client facade

```php

namespace App\Facades;

use Config;
use Ratchet\Client;

class SocketClient
{
    /**
     * Get the registered name of the component.
     *
     * @param string $route
     * @param array  $arg
     */
    public static function send($route, array $arg)
    {
        $config = config('socket');
        Client\connect('ws://' . $config['httpHost'] . ':' . $config['port'] . '/' . $route)->then(function ($conn) use (
            $arg
        ) {
            $conn->send(json_encode($arg));
            $conn->close();
        });
    }
}

```

Model Observer
```php
namespace App\Observers;

use Illuminate\Support\Facades\Artisan;
use Symfony\Component\Process\Process;

class GameObserver
{
    /**
     * @param $game
     *
     * @return mixed
     */
    public function creating($game)
    {
            //
            SocketClient::send('game', [
                'type'    => $game->type,
                'command' => 'winner',
                'winner'  =>  $game->winnerUser,
            ]);
    }
}
```


When I create a model, I send an alert to all clients

**Comment by sarfraznawaz2005** [comment]
@tabuna Thank you so much, I was figuring it out on Pawl but now everything is clear. Thanks once again :)

**Comment by sarfraznawaz2005** [comment]
@tabuna How were you able to connect? when I try i get following error:

Could not connect: DNS Request did not return valid answer.

Code:

```
Client\connect('ws://' . $config['httpHost'] . ':' . $config['port'] . '/notification' )
    ->then(function ($conn)  {
        $conn->send('sarfraz');
        $conn->close();
    }, function ($e) {
        echo "Could not connect: {$e->getMessage()}\n";
    });
```

FYI I am on localhost not online. Any idea please ?

**Comment by tabuna** [comment]
Change localhost

> config/socket.php

localhost => 127.0.0.1
```php
'httpHost' => env('SOCKET_HTTP_HOST', '127.0.0.1'),
```

**Comment by sarfraznawaz2005** [comment]
With that I get differnt error:

**Could not connect: HTTP/1.1 404 Not Found X-Powered-By: Ratchet/0.3.6**

:(

**Comment by sarfraznawaz2005** [comment]
Sorry I restarted and it works now, thanks a million :)

**Comment by anil1712** [comment]
Getting exception here App::getInstance()
