### ISSUE TITLE
Cannot connect on site with https

### ISSUE THREAD

**Issue by sarfraznawaz2005** [TheOrchid/Socket#12]
Hi Alexandr,

I am successfully able to connect to server from non-https site (staging) but when I try to connect on live site which is on https, it just cannot connect.

I researched and found out that mod_proxy.so and mod_proxy_wstunnel.so should be used to proxy requests on apache v 2.4. I do have these modules enabled and right apache version and I have this in my apache config file:

`<VirtualHost *:80>`
`  ProxyPass /wss/ ws://x.x.x.x:8080/`
`</VirtualHost>`

where `x.x.x.x` is site's IP.

Have you been in similar situation or what is your setup in case of https to be able to connect successfully ?

FYI, I am on siteground dedicated server.

**Comment by tabuna** [comment]
Hi, I do not use apache on the server.

Try:

Add this setting to your httpd.conf file
```
ProxyPass /wss2/ ws://x.x.x.x:8080/
```

Use this URL in your JavaSscript call when you want a WSS connection:

```
var ws = new WebSocket("wss://x.x.x.x/wss2/NNN"); //NNN - Your routing
```

Restart Apache web server

**Comment by sarfraznawaz2005** [comment]
thanks,  i will look into this.

**Comment by mabuak** [comment]
hi @sarfraznawaz2005 , can you share your apache conf? because i got timeout in my side.

Thanks

**Comment by mabuak** [comment]
Hi @chantrea, i have example apache conf, hope this will help you.

https://gist.github.com/mabuak/9e170d7e01a11b7c8ca01c6f8b9abc03

**Comment by chantrea** [comment]
@mabuak thank for your quick response can you please look to #35 and give me some advise on that please thank you
