### ISSUE TITLE
XDebug extension detected. Remember to disable this if performance testing or going live!

### ISSUE THREAD

**Issue by Nisthar** [TheOrchid/Socket#2]
I installed the package and configured it correctly. But i am getting the following error when i try to run the serve command.

```
    XDebug extension detected. Remember to disable this if performance testing
    or going live!
```

I am running it in wamp server.

**Comment by tabuna** [comment]
For it is in Ratchet
```php
if (extension_loaded('xdebug')) {
     trigger_error('XDebug extension detected. Remember to disable this if performance testing or going live!', E_USER_WARNING);
}
```

**Comment by Nisthar** [comment]
@tabuna yes. I saw that. But can i just comment it out or disable the plug-in?  I searched and tried many methods to disable xdebug but nothing worked. I tried to disable it in from php.ini
