### ISSUE TITLE
Working with push and subscriptions?

### ISSUE THREAD

**Issue by kikemarto** [TheOrchid/Socket#5]
Hi

The documentation is very small, I would like to know if this library has all the capabilities of the documentation of Ratchet (Both push and subscriptions)

Greetings.

Google Translate.

**Comment by tabuna** [comment]
Hey.

The library is a wrapper over the Ratchet and you can use **all the features** described in Ratchet. (Some may be different from the php artisan socket: seve)

Google Translate.
